### ISSUE TITLE
Configure hot module reloading for devs

### ISSUE THREAD

**Issue by diversemix** [diversemix/malcolm#3]

**Comment by will-byrne** [comment]
## Current status:
### Separated Client Server:
- [x] Hot Module reloading 
- [x] Typescript

### Single Package:
- [ ] Hot Module Reloading (50%)
- [ ] Typescript

## Future work
- [ ] Finish the typescript module for single package. (*)
- [ ] Discuss whether to use one package or the separated client/server

(*)  Getting the typescript working on the front end shouldn't be too much work (less than a day) but will require some effort and research to ensure that we are doing it properly. The only reason it wasn't before was because of errors that made no sense cause by lack of understanding of typescript.

**Comment by diversemix** [comment]
Thanks for the update... I'm mindful we need to choose the right approach.  This sounds like the approach we'll take for a PoC ... but we may want to revisit if this PoC is adopted.

/cc @hdrury1
